### ISSUE TITLE
Bump cats dependency or split out

### ISSUE THREAD

**Issue by frosforever** [atais/Fixed-Length#8]
Current dependency of cats is set to `0.9.0` which is not binary compatible with latest release `1.1.0`.

Two steps to fix this
1) Update the dependency and publish a new version
2) Split out the cats dependency which is only used  in [`Write.scala`](https://github.com/atais/Fixed-Length/blob/5a916c57a04189177dcf43ad17fe6bcf9de5d4e5/src/main/scala/com/github/atais/util/Write.scala#L20-L23) to its own `fixed-length-cats` module that separately published. That way, future binary incompatibilities are easily handled down stream by users without requiring maintainers of `fixed-length` to release another version. 

What do we think?

**Comment by atais** [comment]
Hm.
So strange that I would need to break it one way or the other (cats 0.9 vs 1.x).
Are you sure there is no other way?

For a quick fix, you could shade your dependency on `cats 1.1` in your app.

But it seems strange to me that there is no way to separate those. 
I will try to check on it.

**Comment by atais** [comment]
`0.4` should be available shortly

**Comment by frosforever** [comment]
Thanks for getting this out and thanks for the library! I've found it really useful.

Perhaps I spoke too soon. It seems okay using the `Show` instance (don't hold me to that) but there's the eviction notice in SBT that would ideally be avoided.

Now that cats is aiming for binary compatibility for `1.x.x` this shouldn't be an issue for a while.
